trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: agritech-variables

stages:

- stage: Build
  displayName: "Build Stage"

  jobs:

  - job: Build
    displayName: "Build Application"

    steps:

    - checkout: self

    - script: |
        echo "Repository cloned successfully"
        pwd
        ls -R
      displayName: "Verify Repository"

    - task: JavaToolInstaller@0
      displayName: "Install Java 17"
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    - task: Maven@4
      displayName: "Build Backend"
      inputs:
        mavenPomFile: 'backend/pom.xml'
        goals: 'clean package -DskipTests'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        mavenVersionOption: 'Default'

- stage: Terraform
  displayName: "Terraform Stage"
  dependsOn: Build

  jobs:

  - job: Terraform
    displayName: "Terraform Deployment"

    steps:

    - checkout: self

    - task: TerraformInstaller@1
      displayName: "Install Terraform"
      inputs:
        terraformVersion: 'latest'

    - script: |
        cd infra

        cat > terraform.auto.tfvars <<EOF
        subscription_id = "$(subscription_id)"
        tenant_id       = "$(tenant_id)"
        client_id       = "$(client_id)"
        client_secret   = "$(client_secret)"
        EOF

      displayName: "Create Terraform Variables"

    - task: TerraformTaskV4@4
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: 'infra'
        backendServiceArm: 'agritech-azure-connectionn'
        backendAzureRmUseEntraIdForAuthentication: true

    - task: TerraformTaskV4@4
      displayName: "Terraform Validate"
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: 'infra'

    - task: TerraformTaskV4@4
      displayName: "Terraform Plan"
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: 'infra'
        environmentServiceNameAzureRM: 'agritech-azure-connectionn'

    - task: TerraformTaskV4@4
      displayName: "Terraform Apply"
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: '-auto-approve'
        workingDirectory: 'infra'
        environmentServiceNameAzureRM: 'agritech-azure-connectionn'