version: '3.9'

services:

  mysql:
    image: mysql:8.0
    container_name: agritech-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: agritechdb
      MYSQL_USER: agritech
      MYSQL_PASSWORD: agritech123

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    restart: always

  backend:
    build:
      context: ../backend

    container_name: agritech-backend

    ports:
      - "8080:8080"

    depends_on:
      - mysql

    restart: always

  frontend:
    build:
      context: ../frontend

    container_name: agritech-frontend

    ports:
      - "80:80"

    depends_on:
      - backend

    restart: always

volumes:
  mysql-data: